server:
  port: 5000
  servlet:
    context-path: /api

  error:
    include-binding-errors: always
    include-message: always

app:
  datasource:
    jdbc-url:
    username:
    password:
    pool-size: 30